import Head from 'next/head'
import styled from 'styled-components'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import Video from '../components/Video'
import Content from '../components/Content'
import Footer from '../components/Footer'
import Layout from '../components/Layout'
import bg from '../assets/hero-image.png';


const Body = styled.div`
  height: 90vh;
  background: #fff;
  margin: 0 5em;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>FakeSite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        backgroundImage: `url(${bg.src})`,
        width: '100%',
        height: '103vh',
      }}>
        <Navbar />
        <Hero />
      </div>
      <Body>
        <Video />
        <Content />
        <Footer />
      </Body>
    </div>
  )
}
